### ISSUE TITLE
[Suggestion] Replace wget with GNU-wget

### ISSUE THREAD

**Issue by lbngoc** [willfarrell/docker-crontab#14]
I often use crontab with `wget` command to run my wordpress cronjobs `wget -O /dev/null https://mysite.com/wp-cron.php` , and my website is used SSL connection, nowadays many people are using SSL for their site to get a better security.

`wget` binary default is not supported SSL, I think it will better if we use `GNU wget` as replacement

`Dockerfile`
```
FROM library/docker:stable

ENV HOME_DIR=/opt/crontab
RUN apk add --no-cache --virtual .run-deps bash jq wget \
    && mkdir -p ${HOME_DIR}/jobs ${HOME_DIR}/projects \
    && adduser -S docker -D \
    && sed -i "s/999/99/" /etc/group

...
```

**Comment by willfarrell** [comment]
If you require the use of additional libraries I suggest using this images as your base and creating your own crontab image is the way to go. This keeps this image as small as possible and unbiased towards certain libraries.

Try something like this:
```Dockerfile
FROM willfarrell/crontab

# upgrade wget version for better TLS support
RUN apk add --no-cache --virtual .run-deps wget

COPY config.json ${HOME_DIR}/
```
