### ISSUE TITLE
Making a job without a command

### ISSUE THREAD

**Issue by magneticflux-** [willfarrell/docker-crontab#16]
How would I go about making a job that launches a container and then waits for the container to finish on its own? I have a container that will start, execute its tasks, and stop. Should the `command` parameter wait for the container to finish execution somehow?

**Comment by magneticflux-** [comment]
It appears my issue was the generated script was not executable. Running `chmod 777 my-task.sh` allows the task to run.

**Comment by willfarrell** [comment]
Interesting, can you submit a PR?

**Comment by magneticflux-** [comment]
I've had it working for a while now, I just had to leave the `command` as an empty string.
My working code:
```JSON
[{
    "name":"overviewer-task",
	"comment":"Re-render the overview map",
	"schedule":"@every 30m",
	"command":"",
	"dockerargs":"--rm -v /mc/data/:/home/minecraft/server/:ro -v /mc/overviewer/world:/home/minecraft/render/:rw -e MINECRAFT_VERSION=1.12.2 -e GOOGLE_MAPS_API_KEY=***********",
	"image":"mide/minecraft-overviewer:latest",
	"onstart":true
}]
```
