### ISSUE TITLE
addgroup: gid '999' in use

### ISSUE THREAD

**Issue by PaulLebmann** [willfarrell/docker-crontab#20]
Hi!
It seems the last change in handling the gid and fixing the issues #18 and #17 by getting the gid from the socket has somehow broken my setup.

With Ubuntu 16.04 kernel 4.4.0-130-generic
Docker version 18.03.1-ce, build 9ee9f40

since I pulled the latest version the crontab containers enter a restart loop.
It seems it fetches the correct gid, but another group (ping) already got 999.

Maybe the fix for #13 Commit b89e3125692fe0c80db9414648046a270b4201a2 (adding && sed -i "s/999/99/" /etc/group) should be reapplied.

At least readding the line fixed the issue for me.

best regards and thanks for your great work!
Paul

**Comment by willfarrell** [comment]
Hi @PaulLebmann, I was worried about this so thanks for reporting again. It's one of those bugs that only happens on certain base OS. Which makes it tricky. I'm going to leave this open until I find a solution that works on all OS.

**Comment by PaulLebmann** [comment]
Hey @willfarrell since the container can not know what gid the host OS is using for the socket before checking in docker-entrypoint it maybe the best option is to remove unused entries in /etc/group to reduce the chance to run into this problem.

I tried `find / -exec stat -c '%g' >> groups.txt {} \;` in the running crontab container and with exception of 999 which is my docker socket gid just a few other were in use:
0 (root)
42 (shadow)
5 (tty)
65533 (nogroup)

Interestingly there I found also the gid 1000 used for /user/local/bin/docker* which has no entry in /etc/group.

Since also the base image could change maybe it would be the best during the build of the image which groups are used and remove the unused. Maybe the /etc group could be "cleaned up" with something like

`grep -E ":(0|5|42|65533|1000):" /etc/group > /tmp/group && cat /tmp/group > /etc/group`

where you could use a bash - script to get the used gids into an array which can be used to create a regex to filter the /etc/group down to the necessary minimum version.

Since docker containers should have a single task I suppose the removal of the unused groups shouldn't cause a problem.

Another possible mitigation could be the deletion of groups without any user. Which I guess could be done in a single sed command.

I'm sorry that the creation of the bash script exceeds my skills but maybe the concept can be an improvement to the problem.

best regards,
Paul

**Comment by willfarrell** [comment]
No worries on the bash creation part. What you've posted here is super helpful. I'll try and get a PR together hopefully sooner than later.

**Comment by PaulLebmann** [comment]
Glad to be of use! Thanks!

**Comment by jortkoopmans** [comment]
Hi, also stumbled on this issue, the group 'ping' already has gid 999, preventing the creation of the docker group as defined in the entrypoint script. This results in container crash and restart loops.

OS: Debian Stretch (9) 4.9.110-1 (2018-07-05). Linux kernel 4.9.0-7-amd64
Docker: 18.06.0-ce

I can confirm the successful workaround is applying the 'RUN sed -i "s/999/99/" /etc/group', effectively moving the 'ping' group out of the way (to GID 99), before entrypoint is initiated.

Tracing back the origin of the ping gid seems to end up directly in the alpine-3.7 image, if I'm understanding this correctly. It's not present on my host OS at least.
This bundle here: https://github.com/gliderlabs/docker-alpine/tree/2e371309a9b5dbbfd018c95ad481fc0d6d2e5e2d/versions/library-3.7/x86_64
has the /etc/group file specifying it.

**Comment by willfarrell** [comment]
Merged a possible fix, please re-test.

**Comment by PaulLebmann** [comment]
Your image works for me again under docker 18.09.2 on Ubuntu 18.04.
Thanks @sergey-shambir and @willfarrell !

**Comment by willfarrell** [comment]
It was all @sergey-shambir, thanks to him for some rapid-fire PRs. I'm just sorry I couldn't make time sooner to get them merged in.
