### ISSUE TITLE
Use case: the equivalent of `docker-compose run --rm my_service some_command`

### ISSUE THREAD

**Issue by mnzaki** [willfarrell/docker-crontab#21]
Any hints on how to achieve the equivalent of running a once-only service from a docker-compose file?
Basically I am interested in the service settings (links, volumes, etc) to be defined. Is the only wait to perhaps keep the service running and exec on it?

**Comment by jd1** [comment]
I had the same problem and had to look it up in the code: `docker run` is only used if you provide `image` in the configuration.
My current solution is a configuration like this:
```json
[{
	"name":"myapp",
	"schedule":"* */1 * * *",
	"image": "vimagick/youtube-dl",
	"dockerargs": "-v youtube-dl_data:/data -v youtube-dl_download:/download --rm",
        "command":"..."
}]
```

I don't like that I have to create the volumes outside the docker-compose file, but at least it's working.

**Comment by willfarrell** [comment]
I haven't tried this but, what if you added `docker-compose` to the `crontab` image and used `{ ... "command":"docker-compose ..." ... }`. `image` and `dockerargs` are purely used to create a `docker run` command (`docker run ${DOCKERARGS} ${IMAGE} ${TMP_COMMAND}`).

If you wanted to make a PR documenting how to it, I'm happy to merge it in for other.
