### ISSUE TITLE
Allow environment variables in options

### ISSUE THREAD

**Issue by Lynncubus** [willfarrell/docker-crontab#22]
First of, thanks for this great project. Much simpler and smaller in size than alternatives while keep configurability.

I'm interested in using this, but i have a somewhat blocking issue. Internally i have multiple environments of the same application. A development, testing and acceptation environment, and they're all running on the same server. Their project name is suffixed by the shorthand of their environment. So `myapp_php_dev`, myapp_php_acc`, etc.

Since i can't use variables in the project option, i have to make multiple config files just for every environment. This is of course a solution, but it creates duplicate and unnecessary files. It'd be nice if we could access variables in options so we can create dynamic options based on variables.

Their are obviously more solutions to this problem, like generating a config file before starting the docker project, but I'm just interested if this would be possible and would like to hear your/others about it.

**Comment by willfarrell** [comment]
Based on your setup I would recommend you run one crontab per env and volume mapping the config file so you don't have to create separate images. This is a workaround for your situation.

You shouldn't be running multiple env on a single machine. Personally, when I set up an env it's on its own AWS account, separate VPC, ec2 cluster, basically complete isolation. I do this not only for security and prevent cross env pollution (ie AWS limitations) but to simplify namings of services (no extra logic to handle special cases). 

That said, I am open to allowing ENV to be hard coded into the config. I see some real benefits from allowing that. Draft up a proposal of what you think it should look like and we can go from there.

They would likely be injected like this to allow for dynamic commands: `ENV1=a ENV2=b docker ... ${ENV1} ...`
