### ISSUE TITLE
How to prevent duplicate job ?

### ISSUE THREAD

**Issue by baotran2207** [willfarrell/docker-crontab#32]
Hi, 
i am concerning about how we prevent duplicate jobs ?
EG: @every 2m , we would call command " curl address", and this takes 3m to finish , how could job know previous job is running and wait for that to finish.
Normal case, i use "flock" , but i am not sure do we have that option in config.json?

**Comment by tsvetiligo** [comment]
I test it and find out jobs can't duplicate. Don't need any additional config.

**Comment by willfarrell** [comment]
The service uses `crond`, there is no special handling. If you want additional functionality you'll have to write it yourself. In this case the fact that a curl is taking 3min to request and you need it every 2min means you should probably find a different way to sync that data (ie request just the changes).

**Comment by tsvetiligo** [comment]
You can use `flock` in `crond` command to prevent duplicate job.

original
`10 01 * * 5 sh /root/import.sh`
flock
`10 01 * * 5 /usr/bin/flock -xn /var/lock/import.lock -c 'sh /root/import.sh'`
