### ISSUE TITLE
Timezone Needed

### ISSUE THREAD

**Issue by tohizma** [willfarrell/docker-crontab#35]
Please add tz data in Dockerfile

`ENV TZ="Zone/City"`

`RUN apk add --no-cache --virtual .run-deps gettext bash jq \`
    `&& mkdir -p ${HOME_DIR}/jobs ${HOME_DIR}/projects \`
    `&& adduser -S docker -D \`
    `&& apk add -U tzdata \`
    `&& cp /usr/share/zoneinfo/${TZ} /etc/localtime`

When creating cron file we used to be mentally think in our own time zone, instead doing math calculating into UTC

Thank you

**Comment by willfarrell** [comment]
You could volume map the host time service (that has the timezone set).
