### ISSUE TITLE
Crond since Version 1.0.0 not running

### ISSUE THREAD

**Issue by PaulLebmann** [willfarrell/docker-crontab#39]
Hello,

when I pulled the latest container from dockerhub cron does not run in the container.

I have a working setup on version 0.6.0, to what I had to rollback to. 

When I update the image to 1.0.0 or latest cron does not run in the container. The container does report, that it is healthy, but investigating inside the container if found that /docker-entrypoint autoheal is running. I could not find a crond process.
Also it seems the shellscripts to execute the commands and the crontab entries are not created.

Another point is, that the docker-entrypoint Script does not look anything like the docker-entrypoint on this repo.

Could it be, that the wrong image is pushed to the registry as docker-crontab?
Since I found no other changes here, except of the ones in .github and the documentation, it seems to me the only plausible explanation.

I just dug around and found your docker-autoheal. There in .github/workflows/github-build.yml is the tag willfarrell/crontab: in use.
I have no idea about github workflows but I guess this could be the problem.

Thanks for your great work!
Paul

**Comment by willfarrell** [comment]
Thanks Paul for reporting this and the detailed investigation. I think you may be right. Resolved!
