### ISSUE TITLE
Logs not written on startup execution

### ISSUE THREAD

**Issue by hottehead** [willfarrell/docker-crontab#8]
After setting up a simple example the output of my command is not written to /var/log/crontab/jobs.log.

**config.json**
```
[
  {
    "comment": "My Comment",
    "schedule": "1 * * * *",
    "command": "echo hello world",
    "onstart":true
  }
]
```

**container output**
```
crontab_1        | ##### crontab generation complete #####
crontab_1        | # My Comment
crontab_1        | */1 * * * * /bin/bash /opt/crontab/jobs/MyName.sh
crontab_1        | ##### run commands with onstart #####
crontab_1        | /bin/bash /opt/crontab/jobs/MyName.sh
crontab_1        | crond -f
crontab_1        | Start Cronjob **MyName** My Comment
crontab_1        | hello world
crontab_1        | End Cronjob **MyName** My Comment
```

**jobs.log**
```
... empty ...
```

**Comment by willfarrell** [comment]
Thanks for reporting. This is know. I haven't found a good workaround yet. Open to a PR, It's been awhile since I looked around for a solution.

See https://github.com/willfarrell/docker-crontab/blob/master/docker-entrypoint#L167-171

**Comment by hongkongkiwi** [comment]
Also encountering this, it's been 2 years, any idea on how to fix it?
